# Generated by Django 4.1.4 on 2022-12-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdata',
            name='iname',
            field=models.CharField(max_length=100),
        ),
    ]
